kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: obo-unleash
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: arbeidssokerregistrering-for-veileder
          namespace: paw
          cluster: prod-gcp
        - application: inngar
          namespace: dab
        - application: beslutteroversikt
          namespace: obo
    outbound:
      external:
        - host: team-obo-unleash-api.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: MICROSOFT_GRAPH_URI
      value: https://graph.microsoft.com/v1.0
    - name: MICROSOFT_GRAPH_SCOPE
      value: https://graph.microsoft.com/.default
  envFrom:
    - secret: obo-unleash-api-token
