kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: obo-unleash
  namespace: obo
  labels:
    team: obo
spec:
  image: ghcr.io/navikt/obo-unleash/obo-unleash:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: axsys.prod-fss-pub.nais.io
        - host: team-obo-unleash-web.nav.cloud.nais.io

  env:
    - name: AXSYS_URL
      value: https://axsys.prod-fss-pub.nais.io
    - name: AXSYS_SCOPE
      value: api://prod-fss.org.axsys/.default

  envFrom:
    - secret: obo-unleash-api-token
