apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: obo-unleash
  namespace: obo
  cluster: dev-gcp
  labels:
    team: obo
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: team-obo
  secretName: obo-unleash-api-token
  environment: development
